### ISSUE TITLE
when I run the classifier, the terminal show an error about the tensorboard.

### ISSUE THREAD

**Issue by wuchungming** [hukenovs/hagrid#44]
**the issue in details is as follows:**
[LINE:84] INFO     [2023-07-23 02:56:07,016]  Current device: cuda
[LINE:223] INFO     [2023-07-23 02:56:07,486]  Epoch: 0
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\HaGRID\hagrid\classifier\run.py", line 105, in <module>
    _run_train(args.path_to_config)
  File "D:\HaGRID\hagrid\classifier\run.py", line 85, in _run_train
    TrainClassifier.train(model, conf, train_dataset, test_dataset)
  File "D:\HaGRID\hagrid\classifier\train.py", line 224, in train
    TrainClassifier.run_epoch(
  File "D:\HaGRID\hagrid\classifier\train.py", line 124, in run_epoch
    add_params_to_tensorboard(writer, optimizer_params, epoch, "optimizer", {"params"})
  File "D:\HaGRID\hagrid\classifier\utils.py", line 59, in add_params_to_tensorboard
    writer.add_scalar(f"{obj}/{param}", value, epoch)
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\utils\tensorboard\writer.py", line 387, in add_scalar
    summary = scalar(
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\utils\tensorboard\summary.py", line 279, in scalar
    scalar = make_np(scalar)
  File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\utils\tensorboard\_convert_np.py", line 24, in make_np
    raise NotImplementedError(
NotImplementedError: Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

**How should I deal with it?** I am looking forward to your reply. Thanks for your contributions.

**Comment by vatsalshah1990** [comment]
@wuchungming Did you resolve this? I'm facing the same issue.
